### ISSUE TITLE
Can't install...

### ISSUE THREAD

**Issue by jfklimek** [zachcmathews/LTFilter#2]
I'm trying to use this on Revit 2019 and 2020.. Neither are loading correctly. I'm getting this comment:

![image](https://user-images.githubusercontent.com/61841131/80743930-dee94a80-8aeb-11ea-910f-1bad120ca079.png)

Not sure what the deal is. Thanks for any help.

**Comment by zachcmathews** [comment]
This is caused by a new(ish) Windows security feature that blocks unsigned downloaded executables. For this reason, I plan to re-release both the LTFilter and the KeynotesRTC add-ins as a pyRevit extension in the near future. For now you can do the following to get it running.

Right click the KeynotesRTC.dll and select properties located in the KeynotesRTC folder at
C:\ProgramData\Autodesk\Revit\Addins\2019\KeynotesRTC or similar for 2020.

Then check the checkbox next to the security warning "This file came from another computer and might be blocked to help protect this computer."
![UnblockRevitAddins](https://user-images.githubusercontent.com/5757884/80777469-5b534c00-8b33-11ea-9c50-0c86fa8e1702.PNG)

The steps will be similar for the LTFilter add-in. Let me know if it works!

**Comment by jfklimek** [comment]
Thank you man! This tool is great. Been using revolution keynotes and the overcombersomeness of it had me going crazy. Appreciate the code!

Joseph Klimek
________________________________
